quarkus:
  oidc:
    application-type: service
    client-id: client-id
    credentials:
      secret: client-secret
    auth-server-url: http://oidcserver/realms/name
  http:
    auth:
      permission:
        authenticated:
          paths: /api/v1/sample*
          policy: authenticated
  rest-client:
    "com.example.remote.SampleRemoteService":
      url: http://localhost:8080/api/v1/sample
  oidc-client:
    credentials:
      secret: client-secret
    client-id: client-id
    grant:
      type: client
    enabled: true
    early-tokens-acquisition: false
    auth-server-url: http://oidcserver/realms/name
  log:
    console:
      json: false
  keycloak:
    policy-enforcer:
      enable: false