"%nosecurity":
  quarkus:
    oidc-client:
      enabled: false
    keycloak:
      policy-enforcer:
        enable: false
    oidc:
      enabled: false
    security:
      users:
        embedded:
          enabled: false

"%basicsecurity":
  quarkus:
    security:
      users:
        embedded:
          enabled: true
          plain-text: true
          users:
            admin: admin
          roles:
            admin: admin
    http:
      auth:
        permission:
          authenticated:
            paths: /api/v1/sample*
            policy: authenticated
            enabled: true
    oidc-client:
      enabled: false
    keycloak:
      policy-enforcer:
        enable: false
    oidc:
      enabled: false

"%oidcsecurity":
  quarkus:
    security:
      users:
        embedded:
          enabled: false
    http:
      auth:
        permission:
          authenticated:
            paths: /api/v1/sample*
            policy: authenticated
            enabled: true
    oidc:
      application-type: service
      client-id: client-id
      credentials:
        secret: client-secret
      auth-server-url: http://oidcserver/realms/name
    oidc-client:
      credentials:
        secret: client-secret
      client-id: client-id
      grant:
        type: client
      enabled: true
      early-tokens-acquisition: false
      auth-server-url: http://oidcserver/realms/name

"%mtlssecurity1":
  quarkus:
    oidc-client:
      enabled: false
    keycloak:
      policy-enforcer:
        enable: false
    oidc:
      enabled: false
      auth-server-url: http://nullhost
    security:
      users:
        embedded:
          enabled: false
    http:
      ssl-port: 8444
      ssl:
        certificate:
          key-store-file: META-INF/resources/client.keystore
          key-store-password: password
          trust-store-file: META-INF/resources/server.keystore 
          trust-store-password: password
        client-auth: REQUIRED
      auth:
        permission:
          authenticated:
            paths: /api/v1/sample*
            policy: authenticated
            enabled: true
    

"%mtlssecurity2":
  quarkus:
    oidc-client:
      enabled: false
    keycloak:
      policy-enforcer:
        enable: false
    oidc:
      enabled: false
      auth-server-url: http://nullhost
    security:
      users:
        embedded:
          enabled: false
    http:
      ssl-port: 8443
      ssl:
        certificate:
          key-store-file: META-INF/resources/server.keystore
          key-store-password: password
          trust-store-file: META-INF/resources/client.keystore 
          trust-store-password: password
        client-auth: REQUIRED
      auth:
        permission:
          authenticated:
            paths: /api/v1/sample*
            policy: authenticated
            enabled: true
    

quarkus:
  rest-client:
    "com.example.remote.SampleRemoteService":
      url: https://localhost:8443
  log:
    console:
      json: false
  oidc:
    enabled: true
  oidc-client:
    enabled: true
  keycloak:
    policy-enforcer:
      enable: false
  security:
    users:
      embedded:
        enabled: false
  http:
    auth:
      permission:
        authenticated:
          paths: /api/v1/sample*
          policy: authenticated
          enabled: false
  tls:
    trust-all: true
org:
  eclipse:
    microprofile:
      rest:
        client:
          propagateHeaders: Authorization