quarkus:
  rest-client:
    "com.example.remote.SampleRemoteService":
      url: http://localhost:8080
  oidc-client:
    enabled: false
  log:
    console:
      json: false
  keycloak:
    policy-enforcer:
      enable: false
  oidc:
    enabled: false
  security:
    users:
      embedded:
        enabled: true
        plain-text: true
        users:
          admin: admin
        roles:
          admin: admin
  http:
    auth:
      permission:
        authenticated:
          paths: /api/v1/backend*
          policy: authenticated
org:
  eclipse:
    microprofile:
      rest:
        client:
          propagateHeaders: Authorization